language: java
cache:
  directories:
    - $HOME/.m2

install:
  - install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
  - sudo apt install xvfb
  - Xvfb :2 &

deploy:
  provider: script
  skip_cleanup: true
  script: mvn --settings .travis/settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V deploy
